version: '3.8'

services:
  proxy:
    build: .
    ports:
      - "11435:11434"
    environment:
      - OLLAMA_SERVER=http://10.252.17.12:11434
      - LOG_LEVEL=INFO
      - REQUEST_TIMEOUT=60
      - MAX_RETRIES=3
    volumes:
      - proxy_logs:/var/log/unthink-proxy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost:11434/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - proxy

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  proxy_logs:
  prometheus_data:
  grafana_data: